pipeline:
  name: Build Images
  identifier: Build_Images
  projectIdentifier: Konr
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Konr_Github
        repoName: build-images
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cidemo
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: TestRail
                  identifier: TestRail
                  spec:
                    connectorRef: konrness_Docker_Hub
                    repo: konrness/testrail
                    tags:
                      - 0.<+pipeline.sequenceId>
                    dockerfile: testrail/Dockerfile
                    context: testrail
                    labels:
                      build_id: <+pipeline.sequenceId>
    - stage:
        name: Test
        identifier: Test
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: TestRail
                  identifier: TestRail
                  spec:
                    connectorRef: konrness_Docker_Hub
                    image: konrness/testrail:0.<+pipeline.sequenceId>
                    shell: Sh
                    command: |-
                      cd testrail
                      ./test.sh
              - step:
                  type: Run
                  name: Retag latest
                  identifier: Retag_latest
                  spec:
                    connectorRef: konrness_Docker_Hub
                    image: docker:latest
                    shell: Sh
                    command: |-
                      while ! docker ps ;do
                          echo "Docker not availble yet"
                          sleep 1
                      done
                      echo "Docker DiND ready"

                      docker tag konrness/testrail:0.<+pipeline.sequenceId> konrness/testrail:latest
                      docker push konrness/testrail:latest
                    privileged: true
          infrastructure:
            useFromStage: Build
          sharedPaths:
            - /var/run
          serviceDependencies:
            - identifier: dind
              name: dind
              type: Service
              spec:
                connectorRef: konrness_Docker_Hub
                image: docker:dind
                privileged: true
